import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/global.css'
import backgroundImage from '../../public/men-music-singer-musician-Person-guitarist-228180-wallhere.com.jpg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex items-center justify-center h-screen w-screen text-white overflow-hidden'>{children}</body>
    </html>
  )
}
